requires:
    less: gulp-less
    minify: gulp-minify-css
    concat: gulp-concat
    uglify: gulp-uglify
mimetypes:
    # This section contains the formatters for the css files
    css:
        # In 'prod' mode, use these settings
        prod:
            outputFolder: web/compiled/css  # The output folder for your saving your compiled files
            webPath:      /compiled/css     # The web path for the compiled files
            # Run these tasks on your compiled files
            tasks:
                - { name: less }
                - { name: minify }
                - { name: concat, args: '%filename%' }
            htmlTag: '<link rel="stylesheet" type="text/css" href="{{ asset("%path%") }}">' # custom html tag

        # This is the list of source files to apply the above settings
        files:
            frontend.css: # This is the output filename
                - assets/css/animate.min.css
                - assets/css/swipebox.css
                - assets/vendor/bootstrap-daterangepicker/daterangepicker-bs3.css
                - assets/vendor/bootstrap3-wysihtml5-bower/dist/bootstrap3-wysihtml5.css
                - assets/vendor/jquery-simplecolorpicker/jquery.simplecolorpicker.css
                - vendors/oh/emoji-bundle/Oh/EmojiBundle/vendor/emoji.css
            backend.css:
                - assets/vendor/bootstrap-daterangepicker/daterangepicker-bs3.css
                - assets/css/backend.css

        # Watch these files for changes (optional)
        watch:
            - assets/**/*.less
            - assets/**/*.css

    # This section contains the formatters for your JS files
#    js:
#        prod:
#            outputFolder: web/compiled/js  # Save the files here
#            webPath:      /compiled/js     # Specify the web path
#            tasks:
#                - { name: concat, args: '%filename%' }
#                - { name: uglify, args: { mangle: false } }
#
#        # Here is a list of files to apply the above tasks to
#        files:
#            jquery.js: # This is the output filename
#                - assets/vendor/jquery/jquery.js
#            app.js:
#                - web/html5lightbox/html5lightbox.js
#                - assets/vendor/angular/angular.js
#                - assets/vendor/angular-route/angular-route.js
#                - assets/vendor/angular-sanitize/angular-sanitize.js
#                - assets/js/tmp/angularApp.js/**/*.js

# This is the list of files/paths to search and find the replacement tags to insert the
# generated <script> or stylesheet tags
replacementPaths:
    - web/*.html
    - includes/**/*.html

default:
    - js
    - css